controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_security_logout:
    resource: security.route_loader.logout
    type: service


# config/routes.yaml
admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

technician_dashboard:
    path: /technician/dashboard
    controller: App\Controller\TechnicianController::dashboard

user_dashboard:
    path: /user/dashboard
    controller: App\Controller\UserController::dashboard

app_home:
    path: /
    controller: App\Controller\HomeController::index


app_logout_success:
    path: /logout-success
    controller: App\Controller\LogoutController::logoutSuccess


# Profile Routes
app_profile:
    path: /profile
    controller: App\Controller\ProfileController::index

app_profile_edit:
    path: /profile/edit
    controller: App\Controller\ProfileController::edit

app_profile_change_password:
    path: /profile/change-password
    controller: App\Controller\ProfileController::changePassword


# Admin User Management Routes
admin_user_list:
    path: /admin/users
    controller: App\Controller\AdminController::listUsers

admin_user_edit:
    path: /admin/users/edit/{id}
    controller: App\Controller\AdminController::editUser

admin_user_delete:
    path: /admin/users/delete/{id}
    controller: App\Controller\AdminController::deleteUser
    methods: [POST]


# Tickets

ticket_new:
    path: /ticket/new
    controller: App\Controller\TicketController::new

ticket_list:
    path: /ticket/list
    controller: App\Controller\TicketController::list

